### ISSUE TITLE
Audio is not playing.

### ISSUE THREAD

**Issue by saswatsamal** [SOACodeRoom/Summer-Hacks#5]
I've added the audio dir to main `./audio/tech-house.mp3` and according to me it was working in my Local but when it been deployed the console is throwing an error at line number 59 of `index.html`. [(Link)](https://github.com/SOACodeRoom/Summer-Hacks/blob/8f032bcdfbb7319c3bec9022fb61a91e7de4631e/index.html#L59)

Error Message: 
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

**Comment by RahulAnand442001** [comment]
instead of writing document.querySeector("audio")  change that to **_document.getElementById("audio")_**
also add an id attribute to the <audio> tag like this <audio id="audio"  src="{#sourcepath}"></audio>
